# -*- coding: utf-8 -*-
"""silentsignals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bv1KCT4FD8UruTUXFng8MKYEqxSETu5Q
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt

# Load your keystroke data

df = pd.read_csv('https://raw.githubusercontent.com/AlysaJarrell/SilentSignals/refs/heads/main/keystroke_session.csv')  # use current file name

df.head()

# Drop any incomplete rows
df = df.dropna(subset=['dwell_time', 'flight_time', 'emotion'])

# Convert relevant columns to numeric (force errors to NaN)
cols_to_convert = ['dwell_time', 'flight_time', 'error', 'wpm']
for col in cols_to_convert:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Drop rows where conversion failed
df = df.dropna(subset=cols_to_convert)

df.head()

# Aggregate data: one row per session
session_features = df.groupby('session_id').agg({
    'dwell_time': ['mean', 'std'],
    'flight_time': ['mean', 'std'],
    'error': lambda x: x.iloc[-1],
    'wpm': 'mean',
    'emotion': 'first'  # all rows in a session have the same emotion label
}).reset_index()

# Flatten multi-index column names
session_features.columns = [
    f"{col[0]}_{col[1]}" if col[1] != '<lambda>' else f"{col[0]}_count"
    for col in session_features.columns
]
session_features = session_features.reset_index()

# Drop "Frustrated"  & "Tired" sessions before label encoding (to make the rest of the emotions more accurate)
session_features = session_features[session_features['emotion_first'] != 'Frustrated']
session_features = session_features[session_features['emotion_first'] != 'Tired']

session_features.tail()

# Encode emotion labels
label_encoder = LabelEncoder()
session_features['emotion_encoded'] = label_encoder.fit_transform(session_features['emotion_first'])

# Prepare input and target
X = session_features[['dwell_time_mean', 'dwell_time_std', 'flight_time_mean', 'flight_time_std', 'error_sum', 'wpm_mean']]
y = session_features['emotion_encoded']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

# Build and train the model
clf = RandomForestClassifier(n_estimators=300, random_state=42)
clf.fit(X_train, y_train)

# Evaluate
y_pred = clf.predict(X_test)
print("Classification Report Random Forest:\n")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# Feature Importance Plot
# feature_importances = pd.Series(clf.feature_importances_, index=X.columns)
# feature_importances.sort_values().plot(kind='barh', title='Feature Importance')
# plt.tight_layout()
# plt.show()



# Saving model for later use
import pickle

# Save the model
with open('emotion_classifier_rf.pkl', 'wb') as model_file:
    pickle.dump(clf, model_file)

# Save the label encoder
with open('label_encoder.pkl', 'wb') as encoder_file:
    pickle.dump(label_encoder, encoder_file)